name: dependency review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dr
        uses: actions/dependency-review-action@v4
